import { axiosInstance } from '../api/axiosInstance.js';

export const partnerService = {
  getDashboard: () => axiosInstance.get('/partner/dashboard'),
  getTodayBookings: () => axiosInstance.get('/partner/bookings/today'),
  getPendingBookings: () => axiosInstance.get('/partner/bookings/pending'),
  getCompletedBookings: () => axiosInstance.get('/partner/bookings/completed'),
  getCancelledBookings: () => axiosInstance.get('/partner/bookings/cancelled'),
  getAllBookings: () => axiosInstance.get('/partner/bookings/all'),
  getBookingDetails: (id) => axiosInstance.get(`/partner/bookings/${id}`),
  getWallet: () => axiosInstance.get('/partner/wallet'),
  requestWithdrawal: (amount) => axiosInstance.post('/partner/wallet/withdraw', { amount }),
  addDepositToWallet: (amount) => axiosInstance.post('/partner/wallet/add-money', { amount }),
  getEarnings: () => axiosInstance.get('/partner/earnings'),
  getRating: () => axiosInstance.get('/partner/rating'),
  getProfile: () => axiosInstance.get('/partner/profile'),
  updateProfile: (data) => axiosInstance.put('/partner/profile', data),
  updateAvailability: (data) => axiosInstance.put('/partner/availability', data),
  getNotifications: () => axiosInstance.get('/partner/notifications'),
  getReviews: () => axiosInstance.get('/partner/reviews'),
  uploadDocuments: (formData) => axiosInstance.post('/partner/auth/upload-documents', formData),
  updateSettingsPreferences: (data) => axiosInstance.put('/partner/settings/preferences', data),
  changePassword: (data) => axiosInstance.post('/partner/settings/change-password', data),
  submitComplaint: (data) => axiosInstance.post('/partner/complaints', data),
  getComplaints: () => axiosInstance.get('/partner/complaints'),
  getChatMessages: () => axiosInstance.get('/partner/chat'),
  sendChatMessage: (data) => axiosInstance.post('/partner/chat', data),
  claimJobOffer: (id) => axiosInstance.post(`/partner/bookings/${id}/accept-job`),
  acceptBooking: (id) => axiosInstance.patch(`/bookings/${id}/accept`),
  getServicePackages: (serviceId) => axiosInstance.get(`/partner/services/${serviceId}/packages`),
  addExtraService: (bookingId, data) => axiosInstance.post(`/partner/bookings/${bookingId}/add-extra-service`, data),
  getPayableAmount: (bookingId) => axiosInstance.get(`/partner/bookings/${bookingId}/payable-amount`),
  verifyExtraPayment: (bookingId, data) => axiosInstance.post(`/partner/bookings/${bookingId}/verify-extra-payment`, data),
  getReferralData: () => axiosInstance.get('/partner/referral'),
  getFaqs: () => axiosInstance.get('/partner/faqs'),
  getOfferedServices: (params) => axiosInstance.get('/partner/offered-services', { params }),
  cancelAcceptedBooking: (bookingId, data) => axiosInstance.post(`/partner/bookings/${bookingId}/cancel`, data),
  getAnalytics: (period = 'thisMonth') => axiosInstance.get('/partner/analytics', { params: { period } }),
};
